version: '2'
services:
  jenkins:
    build: ../../docker-images/jenkins
    ports:
     - "1080:8080"
    volumes:
     - jenkins-data:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins-data:
          